on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    # ここが重要：Node.js 24への強制移行を「承諾」する設定
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    container:
      # ZMKビルド環境も最新の3.5を維持
      image: zmkfirmware/zmk-build-arm:3.5
    
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build
        run: west build -s zmk/app -b xiao_ble -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 xiao_ble_firmware.uf2

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: xiao_ble_firmware.uf2
